export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_USER_LOCATION_ERROR = 'SET_USER_LOCATION_ERROR';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const SET_CURRENT_STOP_GROUP = 'SET_CURRENT_STOP_GROUP';

export const SET_ALL_ROUTES_LOADING = 'SET_ALL_ROUTES_LOADING';
export const SET_NEARBY_TRIPS_LOADING = 'SET_NEARBY_TRIPS_LOADING';
export const SET_STOPS_FOR_ROUTE_LOADING = 'SET_STOPS_FOR_ROUTE_LOADING';
export const SET_VEHICLES_LOADING = 'SET_VEHICLES_LOADING';

export const SET_AGENCIES = 'SET_AGENCIES';
export const SET_ROUTES = 'SET_ROUTES';
export const SET_STOPS = 'SET_STOPS';
export const SET_TRIPS = 'SET_TRIPS';
export const SET_SITUATIONS = 'SET_SITUATIONS';

export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_STOP_GROUPS = 'SET_STOP_GROUPS';
export const SET_STOPS_FOR_LOCATION = 'SET_STOPS_FOR_LOCATION';
export const SET_ARRIVALS_AND_DEPARTURES = 'SET_ARRIVALS_AND_DEPARTURES';
