export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_USER_LOCATION_ERROR = 'SET_USER_LOCATION_ERROR';

export const SET_PATHNAME = 'SET_PATHNAME';

export const SET_ROUTES_FOR_AGENCY_LOADING = 'SET_ROUTES_FOR_AGENCY_LOADING';
export const SET_NEARBY_TRIPS_LOADING = 'SET_NEARBY_TRIPS_LOADING';
export const SET_STOPS_FOR_ROUTE_LOADING = 'SET_STOPS_FOR_ROUTE_LOADING';
export const SET_VEHICLES_LOADING = 'SET_VEHICLES_LOADING';

export const SET_REFERENCES = 'SET_REFERENCES';

export const SET_ROUTES = 'SET_ROUTES';
export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_STOP_GROUPS = 'SET_STOP_GROUPS';
export const SET_STOPS_FOR_LOCATION = 'SET_STOPS_FOR_LOCATION';
export const SET_ARRIVALS_AND_DEPARTURES = 'SET_ARRIVALS_AND_DEPARTURES';

export const SET_MAP_BOUNDS = 'SET_MAP_BOUNDS';
export const INCREMENT_MAP_ZOOM = 'INCREMENT_MAP_ZOOM';
export const DECREMENT_MAP_ZOOM = 'DECREMENT_MAP_ZOOM';
