export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_USER_LOCATION_ERROR = 'SET_USER_LOCATION_ERROR';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP';
export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';

export const SET_ALL_ROUTES = 'SET_ALL_ROUTES';
export const SET_ALL_ROUTES_LOADING = 'SET_ALL_ROUTES_LOADING';

export const SET_SELECTED_ROUTE = 'SET_SELECTED_ROUTE';
export const SET_STOP_GROUPINGS_FOR_ROUTE = 'SET_STOP_GROUPINGS_FOR_ROUTE';
export const SET_STOPS_FOR_ROUTE_LOADING = 'SET_STOPS_FOR_ROUTE_LOADING';

export const SET_NEARBY_TRIPS = 'SET_NEARBY_TRIPS';
export const SET_NEARBY_TRIPS_LOADING = 'SET_NEARBY_TRIPS_LOADING';

export const SET_TRIPS_FOR_ROUTE = 'SET_TRIPS_FOR_ROUTE';
export const SET_TRIPS_FOR_ROUTE_LOADING = 'SET_TRIPS_FOR_ROUTE_LOADING';
