export default {
  data: {
    tripsForLocation: [],
    stopsForLocation: [],
    tripsDetailsForRoute: {},
    agencies: {
      disclaimer: '',
      id: '1',
      lang: 'en',
      name: 'Capital Metro',
      phone: '512-474-1200',
      privateService: false,
      timezone: 'America/Chicago',
      url: 'http://www.capmetro.org/',
    },
    routes: {},
    situations: {},
    stops: {},
    trips: {},
    shapes: {},
    tripDetails: {},
  },
  ui: {
    page: 'ROUTE_LIST',
    tab: 'All',
    agency: '1',
    currentRoute: null,
    stop: null,
    vehicle: null,
    errorMessage: null,
    userLatLng: null,
    tripsForLocationLoading: false,
    tripsDetailsForRouteLoading: false,
  },
};
